---

- name: "Make sure {{ postgresql_data_dir }}/{{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }} is symlink"
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/{{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }}"
  register: sym

- block:  # synchronize WAL`s if wal dir exist (and is not symlink)
    - name: Make sure rsync is installed (for synchronize wal dir)
      ansible.builtin.package:
        name:
          - rsync
          - sshpass
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"

    - name: Stop patroni service (for create symlink)
      ansible.builtin.systemd:
        name: patroni
        state: stopped
      register: patroni_stop_result

    - name: Make sure PostgreSQL is stopped
      become: true
      become_user: postgres
      ansible.builtin.command: "{{ postgresql_bin_dir }}/pg_ctl status -D {{ postgresql_data_dir }}"
      register: stop_result
      changed_when: false
      failed_when: false
      until: stop_result.rc == 3
      retries: 100
      delay: 6

    - name: "Synchronize {{ postgresql_data_dir }}/{{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }} to {{ postgresql_wal_dir }}"
      become: true
      become_user: postgres
      ansible.posix.synchronize:
        src: "{{ postgresql_data_dir }}/{{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }}/"
        dest: "{{ postgresql_wal_dir }}/"
      delegate_to: "{{ inventory_hostname }}"

    # ğŸ”„ Determine base pg_wal_dir name
    - name: Roles.patroni.custom_wal_dir | Set pg_wal_dir based on postgresql_version
      ansible.builtin.set_fact:
        pg_wal_dir: "{{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }}"

    - name: "Rename {{ pg_wal_dir }} to {{ pg_wal_dir }}_old"
      ansible.builtin.command: mv {{ postgresql_data_dir }}/{{ pg_wal_dir }} {{ postgresql_data_dir }}/{{ pg_wal_dir }}_old
      register: mv_result
  when: sym.stat.exists and not sym.stat.islnk|bool

- name: "Create symlink {{ postgresql_data_dir }}/{{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }} -> {{ postgresql_wal_dir }}"
  become: true
  become_user: postgres
  ansible.builtin.file:
    src: "{{ postgresql_wal_dir }}"
    dest: "{{ postgresql_data_dir }}/{{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }}"
    state: link
  when: sym.stat.islnk is not defined or not sym.stat.islnk|bool

- block:  # start patroni
    - name: Start patroni service
      ansible.builtin.systemd:
        name: patroni
        state: started

    - name: "Wait for port {{ patroni_restapi_port }} to become open on the host"
      ansible.builtin.wait_for:
        port: "{{ patroni_restapi_port }}"
        host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
        state: started
        timeout: 120
        delay: 10
      ignore_errors: false

    - name: Check that the patroni is healthy
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:{{ patroni_restapi_port }}/health"
        status_code: 200
      register: replica_result
      until: replica_result.status == 200
      retries: 120
      delay: 10
  when: patroni_stop_result is changed

- name: "Remove {{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }}_old directory"
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}/{{ 'pg_wal' if postgresql_version is version('10', '>=') else 'pg_xlog' }}_old"
    state: absent
  when:
    - replica_result.status is defined
    - replica_result.status == 200

...
