---
# https://pip.pypa.io/en/stable/installing/
# Python 2.7 reached the end of its life on January 1st, 2020.
# A future version of pip will drop support for Python 2.7.
# Installing latest version pip3 for python3

# install pip package from repo
- block:  # with get-pip.py
    - name: pip | get-pip.py
      get_url:
        url: "{{ item }}"
        dest: /tmp/
        timeout: 60
        validate_certs: false
      loop:
        - "{{ pip_package_repo }}"
      register: get_pip_result

    - name: pip | install pip
      command: >
        python3 {{ pip_package_repo | basename }}
        --trusted-host=pypi.python.org
        --trusted-host=pypi.org
        --trusted-host=files.pythonhosted.org
      args:
        chdir: /tmp/
      when: get_pip_result.changed
  environment: "{{ proxy_env | default({}) }}"
  when: pip_package_repo is search("get-pip.py") and
        proxy_env is defined and proxy_env | length > 0

- block:  # with tar.gz
    - name: pip | download pip package
      get_url:
        url: "{{ item }}"
        dest: /tmp/
        timeout: 60
        validate_certs: false
      loop:
        - "{{ pip_package_repo }}"
      register: pip_package_result

    - name: pip | extract pip package into /tmp
      unarchive:
        src: "/tmp/{{ pip_package_repo | basename }}"
        dest: /tmp/
        extra_opts:
          - --no-same-owner
        remote_src: true

    - name: pip | install pip
      command: "python3 setup.py install"
      args:
        chdir: "/tmp/{{ pip_package_repo.split('.tar.gz')[0] | basename }}"
      when: pip_package_result.changed
  when: pip_package_repo is search("tar.gz")

...
