---
# File: config_windows.yml - Consul configuration tasks for Windows

- name: Create configuration
  ansible.windows.win_copy:
    dest: "{{ config_item.dest }}"
    content: "{{ lookup('template', consul_config_template_path, convert_data=True) | to_nice_json }}"
  with_items:
    - dest: "{{ consul_config_path }}/config.json"
      config_version: "{{ consul_node_role }}"
      when: true
    - dest: "{{ consul_config_path }}/bootstrap.json"
      config_version: "bootstrap"
      when: "{{ consul_debug | bool }}"
    - dest: "{{ consul_config_path }}/server.json"
      config_version: "server"
      when: "{{ consul_debug | bool }}"
    - dest: "{{ consul_config_path }}/client.json"
      config_version: "client"
      when: "{{ consul_debug | bool }}"
  loop_control:
    loop_var: config_item
  when:
    - config_item.when
  notify:
    - restart consul

- name: Create custom configuration
  ansible.windows.win_copy:
    dest: "{{ consul_configd_path }}/50custom.json"
    content: "{{ lookup('template', 'templates/configd_50custom.json.j2', convert_data=True) | to_nice_json }}"
  when:
    - consul_config_custom is defined
  notify:
    - restart consul

- name: Get Windows path for custom configuration file
  ansible.windows.win_stat:
    path: "{{ consul_configd_path }}/50custom.json"
  register: custom_config_win_path

- name: Set fact list with custom configuration file
  set_fact:
    managed_files: "{{ managed_files |default([]) }} + \
      [ '{{ custom_config_win_path.results[0].stat.path }}' ]"
  when: custom_config_win_path.stat.exists
