---
# File: dnsmasq.yml - Dnsmasq tasks for Consul

- name: Install Dnsmasq package
  package:
    name: "{{ dnsmasq_package }}"
    state: present
  become: true
  tags: dnsmasq, installation

- name: Create Dnsmasq configuration directory
  file:
    path: /usr/local/etc/dnsmasq.d
    state: directory
    owner: root
    group: wheel
    mode: 0700
  become: true
  when: ansible_os_family == "FreeBSD"
  tags: dnsmasq

- name: Include Dnsmasq configuration directory
  lineinfile:
    dest: /usr/local/etc/dnsmasq.conf
    line: 'conf-dir=/usr/local/etc/dnsmasq.d/,*.conf'
  become: true
  notify: restart dnsmasq
  when: ansible_os_family == "FreeBSD"
  tags: dnsmasq

- name: Create Dnsmasq configuration
  template:
    src: dnsmasq-10-consul.j2
    dest: "{{ dnsmasq_item.dest }}"
    owner: root
    group: "{{ dnsmasq_item.group }}"
    mode: 0644
  become: true
  notify: restart dnsmasq
  when: "{{ dnsmasq_item.when }}"
  tags: dnsmasq
  loop:
    - { dest: '/etc/dnsmasq.d/10-consul', group: 'root', when: ansible_os_family|lower != "freebsd" }
    - { dest: '/usr/local/etc/dnsmasq.d/consul.conf', group: 'wheel', when: ansible_os_family|lower == "freebsd" }
  loop_control:
    loop_var: dnsmasq_item

- name: Disable systemd-resolved
  when: ansible_service_mgr == "systemd"
  block:

    - name: Disable systemd-resolved service
      service:
        name: systemd-resolved
        enabled: false
        state: stopped
      become: true

    - name: Check if resolv.conf is pointing to systemd-resolved
      stat:
        path: /etc/resolv.conf
      register: resolv_dot_conf

    - name: Remove resolv.conf association with systemd-resolved
      file:
        src: /run/resolvconf/resolv.conf
        path: /etc/resolv.conf
        state: link
      become: true
      when:
        - resolv_dot_conf.stat.islnk
        - 'resolv_dot_conf.stat.lnk_source == "/run/systemd/resolve/stub-resolv.conf"'
