---
# File: install_remote.yml - package installation tasks for Consul

- name: Install OS packages
  ansible.builtin.package:
    name: "{{ consul_os_packages }}"
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  tags: installation

- name: Validate remote Consul directory
  ansible.builtin.tempfile:
    state: directory
    prefix: ansible-consul.
  register: consul_temp_dir

- name: Download and unarchive Consul
  block:
    - name: Read Consul package checksum file
      ansible.builtin.stat:
        path: "{{ consul_temp_dir.path }}/consul_{{ consul_version }}_SHA256SUMS"
      register: consul_checksum
      changed_when: false
      tags: installation

    - name: Download Consul package checksum file
      ansible.builtin.get_url:
        url: "{{ consul_checksum_file_url }}"
        dest: "{{ consul_temp_dir.path }}/consul_{{ consul_version }}_SHA256SUMS"
        validate_certs: false
      tags: installation
      when: not consul_checksum.stat.exists | bool

    - name: Read Consul package checksum
      ansible.builtin.shell: "grep {{ consul_pkg }} {{ consul_temp_dir.path }}/consul_{{ consul_version }}_SHA256SUMS"
      register: consul_sha256
      changed_when: false
      tags:
        - installation
        - skip_ansible_lint

    - name: Download Consul
      ansible.builtin.get_url:
        url: "{{ consul_zip_url }}"
        dest: "{{ consul_temp_dir.path }}/{{ consul_pkg }}"
        checksum: "sha256:{{ consul_sha256.stdout.split(' ') | first }}"
        timeout: 42
      register: consul_download
      tags: installation

    - name: Unarchive Consul and install binary
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ consul_temp_dir.path }}/{{ consul_pkg }}"
        dest: "{{ consul_bin_path }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: "0755"
      register: consul_install
      notify:
        - restart consul
        - reload systemd daemon
      when: consul_download is changed
      tags: installation
  always:
    - name: Cleanup
      ansible.builtin.file:
        path: "{{ consul_temp_dir.path }}"
        state: absent
      tags: installation
