---

# Hostname
- import_tasks: ../tasks/hostname.yml
  when: hostname is defined and hostname | length > 0
  ignore_errors: yes
  tags: [ hostname, configure ]

# Kernel
- import_tasks: ../tasks/sysctl.yml
  when: sysctl_conf is defined and sysctl_conf | length > 0
  ignore_errors: yes
  tags: [ sysctl, kernel, configure ]

# Transparent Huge Pages
- import_tasks: ../tasks/transparent_huge_pages.yml
  when: disable_thp is defined and disable_thp == "true"
  ignore_errors: yes
  tags: [ disable_thp, configure ]

# limits
- import_tasks: ../tasks/pam_limits.yml
  when: set_limits is defined and set_limits == "true"
  ignore_errors: yes
  tags: [ limits, configure ]

# I/O Scheduler
- import_tasks: ../tasks/io_scheduler.yml
  when: (set_scheduler is defined) and (set_scheduler == "true") and (scheduler | length > 0)
  ignore_errors: yes
  tags: [ scheduler, configure ]

# Locales
- import_tasks: ../tasks/locales.yml
  when: locales is defined and locales | length > 0
  ignore_errors: yes
  tags: [ locales, configure ]

# TimeZone
- import_tasks: ../tasks/timezone.yml
  when: timezone is defined and timezone | length > 0
  ignore_errors: yes
  tags: [ timezone, configure ]

# NTP
- import_tasks: ../tasks/ntp.yml
  when: ntp_enabled is defined and ntp_enabled == "true"
  ignore_errors: yes
  tags: [ ntp, configure ]

# SSH Keys
- import_tasks: ../tasks/ssh-keys.yml
  when: enable_SSH_Key_based_authentication is defined and enable_SSH_Key_based_authentication == "true"
  ignore_errors: yes
  tags: [ ssh_keys, configure ]

