---

# Install packages from files
- block:
    - name: copy packages into /tmp
      copy:
        src: '{{ item }}'
        dest: /tmp/
      loop: "{{ packages_from_file }}"
      register: copy_packages_result

    - name: Install packages
      apt:
        force_apt_get: yes
        deb: '/tmp/{{ item }}'
        state: present
      loop: "{{ packages_from_file | map('basename') | list }}"
      when: ansible_os_family == "Debian" and copy_packages_result.changed

    - name: Install packages
      package:
        name: '/tmp/{{ item }}'
        state: present
      loop: "{{ packages_from_file | map('basename') | list }}"
      when: ansible_os_family == "RedHat" and copy_packages_result.changed
  when: packages_from_file is defined and packages_from_file | length > 0
  tags: install_packages_from_file

# Install packages from repository
- name: Install | system packages
  package:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ system_packages }}"
  environment: '{{ proxy_env | default({}) }}'
  when: installation_method == "repo"
  tags: install_packages

# PostgreSQL prepare for install (for Debian based only)
- block:
    - name: Install | PostgreSQL | ensure postgresql database-cluster manager package
      package:
        name: postgresql-common
        state: present
      environment: '{{ proxy_env | default({}) }}'

    - name: Install | PostgreSQL | disable initializing of a default postgresql cluster
      replace:
        path: /etc/postgresql-common/createcluster.conf
        replace: create_main_cluster = false
        regexp: ^#?create_main_cluster.*$

    - name: Install | PostgreSQL | disable log rotation with logrotate for postgresql (use logging_collector)
      file:
        dest: /etc/logrotate.d/postgresql-common
        state: absent
  when: installation_method == "repo" and ansible_os_family == "Debian"
  tags: install_postgres

# PostgreSQL prepare for install (for RHEL 8)
- block:
    - name: Install | PostgreSQL | check if appstream module is enabled
      command: 'dnf -y -C module list postgresql'
      register: postgresql_module_result
      changed_when: false
      args:
        warn: false

    - name: Install | PostgreSQL | disable appstream module
      command: 'dnf -y -C module disable postgresql'
      args:
        warn: false
      when: "'[x] ' not in postgresql_module_result.stdout"
  when: installation_method == "repo" and (ansible_os_family == "RedHat" and ansible_distribution_major_version >= '8')
  ignore_errors: yes
  tags: install_postgres

# Install PostgreSQL from repository
- name: Install | PostgreSQL packages
  package:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ postgresql_packages }}"
  environment: '{{ proxy_env | default({}) }}'
  when: installation_method == "repo" and postgresql_exists != "true"
  tags: install_postgres
