---

- name: Make sure the PostgreSQL users are present
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    encrypted: true
    role_attr_flags: "{{ item.flags }}"
    login_host: "127.0.0.1"
    login_port: "{{ postgresql_port }}"
    login_user: "{{ patroni_superuser_username }}"
    login_password: "{{ patroni_superuser_password }}"
    login_db: "postgres"
    state: present
  ignore_errors: true
  loop: "{{ postgresql_users | flatten(1) }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgresql_users | default('') | length > 0
    - item.password | default('') | length > 0  # Ensure the password is not empty
    - patroni_standby_cluster.host | default('') | length < 1  # do not perform on the Standby Cluster leader
  tags: postgresql_users

- name: Grant roles to users
  community.postgresql.postgresql_membership:
    group: "{{ item.role | default('') }}"
    target_role: "{{ item.name }}"
    login_host: "127.0.0.1"
    login_port: "{{ postgresql_port }}"
    login_user: "{{ patroni_superuser_username }}"
    login_password: "{{ patroni_superuser_password }}"
    state: present
  ignore_errors: true
  loop: "{{ postgresql_users | flatten(1) }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgresql_users | default('') | length > 0
    - item.role | default('') | length > 0
    - patroni_standby_cluster.host | default('') | length < 1  # do not perform on the Standby Cluster leader
  tags: postgresql_users

...
