---
# Generate passwords (if not defined)
- block:
    - name: Generate a password for patroni superuser
      ansible.builtin.set_fact:
        patroni_superuser_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
      run_once: true
      delegate_to: "{{ groups['master'][0] }}"
      when: patroni_superuser_password | default('') | length < 1

    - name: Generate a password for patroni replication user
      ansible.builtin.set_fact:
        patroni_replication_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
      run_once: true
      delegate_to: "{{ groups['master'][0] }}"
      when: patroni_replication_password | default('') | length < 1

    - name: Generate a password for patroni restapi
      ansible.builtin.set_fact:
        patroni_restapi_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
      run_once: true
      delegate_to: "{{ groups['master'][0] }}"
      when: patroni_restapi_password | default('') | length < 1

    - name: Generate a password for pgbouncer auth user
      ansible.builtin.set_fact:
        pgbouncer_auth_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
      run_once: true
      delegate_to: "{{ groups['master'][0] }}"
      when:
        - pgbouncer_install | bool
        - pgbouncer_auth_user | bool
        - pgbouncer_auth_password | default('') | length < 1
  when:
    - not (postgresql_cluster_maintenance | default(false) | bool) # exclude for config_pgcluster.yml
    - not (new_node | default(false) | bool) # exclude for add_pgnode.yml

# Get current passwords (if not defined) - for config_pgcluster.yml
- block:
    - name: Get patroni superuser password
      ansible.builtin.shell: |
        set -o pipefail;
        grep -A10 "authentication:" /etc/patroni/patroni.yml | \
        grep -A3 "superuser" | grep "password:" | awk '{ print $2 }' | tail -n 1
      args:
        executable: /bin/bash
      run_once: true
      delegate_to: "{{ groups['master'][0] }}"
      register: superuser_password_result
      changed_when: false  # This tells Ansible that this task doesn't change anything
      when: patroni_superuser_password | default('') | length < 1

    - name: Get patroni replication user password
      ansible.builtin.shell: |
        set -o pipefail;
        grep -A10 "authentication:" /etc/patroni/patroni.yml | \
        grep -A3 "replication" | grep "password:" | awk '{ print $2 }' | tail -n 1
      args:
        executable: /bin/bash
      run_once: true
      delegate_to: "{{ groups['master'][0] }}"
      register: replication_password_result
      changed_when: false  # This tells Ansible that this task doesn't change anything
      when: patroni_replication_password | default('') | length < 1

    - name: Get patroni restapi password
      ansible.builtin.shell: |
        set -o pipefail;
        grep -A10 "restapi:" /etc/patroni/patroni.yml | \
        grep -A3 "authentication" | grep "password:" | awk '{ print $2 }' | tail -n 1
      args:
        executable: /bin/bash
      run_once: true
      delegate_to: "{{ groups['master'][0] }}"
      register: patroni_restapi_password_result
      changed_when: false  # This tells Ansible that this task doesn't change anything
      when: patroni_restapi_password | default('') | length < 1

    - name: "Set variable: patroni_superuser_password"
      ansible.builtin.set_fact:
        patroni_superuser_password: "{{ superuser_password_result.stdout }}"
      when: superuser_password_result.stdout is defined

    - name: "Set variable: patroni_replication_password"
      ansible.builtin.set_fact:
        patroni_replication_password: "{{ replication_password_result.stdout }}"
      when: replication_password_result.stdout is defined

    - name: "Set variable: patroni_restapi_password"
      ansible.builtin.set_fact:
        patroni_restapi_password: "{{ patroni_restapi_password_result.stdout }}"
      when: patroni_restapi_password_result.stdout is defined
  when:
    - (postgresql_cluster_maintenance | default(false) | bool)
      or (new_node | default(false) | bool) # include for add_pgnode.yml
