---
- name: '[Pre-Check] (ALL) Test PostgreSQL DB Access'
  ansible.builtin.command: >
    psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc 'select 1'
  changed_when: false

- name: '[Pre-Check] Make sure that physical replication is active'
  ansible.builtin.command: >-
    psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc
    "select count(*) from pg_stat_replication
    where application_name != 'pg_basebackup'"
  register: pg_replication_state
  changed_when: false
  when:
    - inventory_hostname in groups['primary']

# Stop, if there are no active replicas
- name: "Pre-Check error. Print physical replication state"
  ansible.builtin.fail:
    msg: "There are no active replica servers (pg_stat_replication returned 0 entries)."
  when:
    - inventory_hostname in groups['primary']
    - pg_replication_state.stdout | int == 0

- name: '[Pre-Check] Make sure there is no high replication lag (more than {{ max_replication_lag_bytes | human_readable }})'
  ansible.builtin.command: >-
    psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc
    "select pg_wal_lsn_diff(pg_current_wal_lsn(),replay_lsn) pg_lag_bytes
    from pg_stat_replication
    order by pg_lag_bytes desc limit 1"
  register: pg_lag_bytes
  changed_when: false
  failed_when: false
  until: pg_lag_bytes.stdout|int < max_replication_lag_bytes|int
  retries: 30
  delay: 5
  when:
    - inventory_hostname in groups['primary']

# Stop, if replication lag is high
- block:
    - name: "Print replication lag"
      ansible.builtin.debug:
        msg: "Current replication lag:
          {{ pg_lag_bytes.stdout | int | human_readable }}"

    - name: "Pre-Check error. Please try again later"
      ansible.builtin.fail:
        msg: High replication lag on the Patroni Cluster, please try again later.
  when:
    - pg_lag_bytes.stdout is defined
    - pg_lag_bytes.stdout|int >= max_replication_lag_bytes|int

- name: '[Pre-Check] Make sure there are no long-running transactions (more than {{ max_transaction_sec }} seconds)'
  ansible.builtin.command: >-
    psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc
    "select pid, usename, client_addr, clock_timestamp() - xact_start as xact_age,
      state, wait_event_type ||':'|| wait_event as wait_events,
      left(regexp_replace(query, E'[ \\t\\n\\r]+', ' ', 'g'),100) as query
      from pg_stat_activity
      where clock_timestamp() - xact_start > '{{ max_transaction_sec }} seconds'::interval
      and backend_type = 'client backend' and pid <> pg_backend_pid()
      order by xact_age desc limit 10"
  register: pg_long_transactions
  changed_when: false
  failed_when: false
  until: pg_long_transactions.stdout | length < 1
  retries: 30
  delay: 2

# Stop, if long-running transactions detected
- block:
    - name: "Print long-running (>{{ max_transaction_sec }}s) transactions"
      ansible.builtin.debug:
        msg: "{{ pg_long_transactions.stdout_lines }}"

    - name: "Pre-Check error. Please try again later"
      ansible.builtin.fail:
        msg: long-running transactions detected (more than {{ max_transaction_sec }} seconds), please try again later.
  when:
    - pg_long_transactions.stdout is defined
    - pg_long_transactions.stdout | length > 0
...
