---

- block:
    # Debian
    - name: Install ntp package
      ansible.builtin.package:
        name: ntp
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      when: ansible_os_family == "Debian"
      tags: ntp_install

    - name: Copy the ntp.conf file
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
      notify: "restart ntp"
      when: ansible_os_family == "Debian"
      tags: ntp_conf

    # RedHat
    - name: Install chrony package
      ansible.builtin.package:
        name: chrony
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      tags: ntp_install
      when: ansible_os_family == "RedHat"

    - name: Copy the chrony.conf template file
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
      notify: "restart chronyd"
      tags: ntp_conf
      when: ansible_os_family == "RedHat"
  when: ntp_enabled is defined and ntp_enabled|bool
  tags: ntp

...
