---
# yamllint disable rule:line-length

- name: Make sure handlers are flushed immediately
  meta: flush_handlers

- name: Make sure the unzip/tar packages are present
  package:
    name:
      - unzip
      - tar
    state: present
  environment: "{{ proxy_env | default({}) }}"
  tags: etcd, etcd_install

- block:  # install etcd package from repo
    - name: Download "etcd" package
      get_url:
        url: "{{ item }}"
        dest: /tmp/
        timeout: 60
        validate_certs: false
      loop:
        - "{{ etcd_package_repo }}"
      environment: "{{ proxy_env | default({}) }}"

    - name: Extract "etcd" into /tmp
      unarchive:
        src: "/tmp/{{ etcd_package_repo | basename }}"
        dest: /tmp/
        extra_opts:
          - --no-same-owner
        remote_src: true

    - name: Copy "etcd" and "etcdctl" binary files to /usr/local/bin/
      copy:
        src: "/tmp/{{ etcd_package_repo.split('.tar.gz')[0] | basename }}/{{ item }}"
        dest: /usr/local/bin/
        mode: u+x,g+x,o+x
        remote_src: true
      loop:
        - etcd
        - etcdctl
  when: installation_method == "repo" and etcd_package_repo | length > 0
  tags: etcd, etcd_install

- block:  # install etcd package from file
    - name: Extract "etcd" into /tmp
      unarchive:
        src: "{{ etcd_package_file }}"
        dest: /tmp/
        extra_opts:
          - --no-same-owner

    - name: Copy "etcd" and "etcdctl" binary files to /usr/local/bin/
      copy:
        src: "/tmp/{{ etcd_package_file.split('.tar.gz')[0] | basename }}/{{ item }}"
        dest: /usr/local/bin/
        mode: u+x,g+x,o+x
        remote_src: true
      loop:
        - etcd
        - etcdctl
  when: installation_method == "file" and etcd_package_file | length > 0
  tags: etcd, etcd_install

- name: Add etcd user
  user:
    name: etcd
    shell: /usr/sbin/nologin
    home: "{{ etcd_data_dir }}"
  tags: etcd, etcd_conf

- name: Create etcd conf directory
  file:
    path: /etc/etcd
    state: directory
  tags: etcd, etcd_conf

- name: Generate conf file "/etc/etcd/etcd.conf"
  template:
    src: templates/etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  tags: etcd, etcd_conf

- name: Copy systemd service file
  template:
    src: templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  tags: etcd, etcd_conf

- name: Enable and start etcd service
  systemd:
    daemon_reload: true
    name: etcd
    enabled: true
    state: started
  tags: etcd, etcd_start

- name: Wait for port 2379 to become open on the host
  wait_for:
    port: 2379
    host: 127.0.0.1
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  tags: etcd, etcd_start

- block:
    - name: Wait until the etcd cluster is healthy
      command: /usr/local/bin/etcdctl cluster-health
      environment:
        ETCDCTL_API: 2
      register: etcd_health_result
      run_once: true
      changed_when: false
      until: "'cluster is healthy' in etcd_health_result.stdout"
      retries: 10
      delay: 10
      ignore_errors: false

    - name: cluster health
      run_once: true
      debug:
        var: etcd_health_result.stdout_lines
  tags: etcd, etcd_start, etcd_status

...
