---

- name: Restart pgbouncer service
  ansible.builtin.systemd:
    name: pgbouncer
    enabled: true
    state: restarted
  listen: "restart pgbouncer"

- name: Wait for port "{{ pgbouncer_listen_port }}" to become open on the host
  ansible.builtin.wait_for:
    port: "{{ pgbouncer_listen_port }}"
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    state: started
    timeout: 120
    delay: 5
  ignore_errors: false
  listen: "restart pgbouncer"

- name: Reload pgbouncer service
  ansible.builtin.systemd:
    name: pgbouncer
    state: reloaded
  listen: "reload pgbouncer"
  ignore_errors: true  # Added to prevent test failures in CI.

...
