---

- name: Get a list of databases
  ansible.builtin.command: >-
    {{ pg_new_bindir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc
    "select datname from pg_catalog.pg_database where datname <> 'template0'"
  register: databases_list
  until: databases_list is success
  delay: 5
  retries: 3
  changed_when: false
  ignore_errors: true  # show the error and continue the playbook execution
  when:
    - inventory_hostname in groups['primary']

- name: Update extensions in each database
  ansible.builtin.include_tasks: update_extensions.yml
  loop: "{{ databases_list.stdout_lines }}"
  loop_control:
    loop_var: pg_target_dbname
  when:
    - databases_list is success
    - databases_list.stdout_lines is defined
    - databases_list.stdout_lines | length > 0

...
