---
# Disable auto failover â€“ we need this to be able to stop leader before its standbys
- name: Pause Patroni cluster (enable maintenance mode)
  become: true
  become_user: postgres
  ansible.builtin.command: "patronictl -c {{ patroni_config_file }} pause --wait {{ patroni_cluster_name }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
    - inventory_hostname in groups['primary']

# Enable maintenance mode for HAProxy
# if 'pgbouncer_install' is 'true' and 'pgbouncer_pool_pause' is 'true'
# we temporarily disable http-checks in order to keep database connections after stopping the Patroni service
# and then pause the pgbouncer pools.
- block:
    - name: Stop confd service
      ansible.builtin.service:
        name: confd
        state: stopped

    - name: Update conf file "/etc/haproxy/haproxy.cfg"
      ansible.builtin.template:
        src: templates/haproxy-no-http-checks.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        group: haproxy

    - name: Reload haproxy service
      ansible.builtin.systemd:
        name: haproxy
        state: reloaded
  become: true
  become_user: root
  ignore_errors: true
  when:
    - with_haproxy_load_balancing | bool
    - pgbouncer_install | bool
    - pgbouncer_pool_pause | bool

# Stop Patroni
- name: Stop Patroni service
  become: true
  become_user: root
  ansible.builtin.service:
    name: patroni
    state: stopped

- name: Wait until the Patroni cluster is stopped
  ansible.builtin.shell: |
    set -o pipefail;
    patronictl -c {{ patroni_config_file }} list -f json | grep -cv '^\[\]$'
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"
  register: patronictl_result
  until: patronictl_result.stdout|int == 0
  retries: 30  # max duration 5 minutes
  delay: 10
  changed_when: false
  failed_when: false
  when:
    - inventory_hostname in groups['primary']

...
