---

- name: Make sure handlers are flushed immediately
  meta: flush_handlers

- block:
    - name: Build a sysctl_conf dynamic variable
      set_fact:
        sysctl_conf_dynamic_var: "{{ sysctl_conf_dynamic_var | default([]) + (sysctl_conf[item] | default([]) | flatten(1)) }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"

    - name: Setting kernel parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
      loop: "{{ sysctl_conf_dynamic_var | default([]) | unique }}"
      when: sysctl_conf_dynamic_var | default([]) | length > 0
  ignore_errors: true
  when: sysctl_set|bool
  tags: sysctl, kernel

...
