---

- name: Start disable-transparent-huge-pages service
  ansible.builtin.systemd:
    daemon_reload: true
    name: disable-transparent-huge-pages
    state: restarted
    enabled: true
  listen: "restart disable-thp"
  when: not ansible_check_mode

...
