---

- block:  # Debian family
    - name: Make sure the gnupg, apt-transport-https and python3-debian packages are present
      ansible.builtin.apt:
        pkg:
          - gnupg
          - apt-transport-https
          - python3-debian
        state: present
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3

    - name: Add pgdg repository and signing key
      ansible.builtin.deb822_repository:
        name: "{{ pg_probackup_repo_name | default('pg_probackup') }}"
        types: [deb]
        uris: "http://repo.postgrespro.ru/pg_probackup/deb/"
        signed_by: "https://repo.postgrespro.ru/pg_probackup/keys/GPG-KEY-PG-PROBACKUP"
        suites: "{{ ansible_distribution_release }}"
        components: "main-{{ ansible_distribution_release }}"
        state: present
        enabled: true
      when: ansible_os_family == "Debian"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3

    - name: Install pg_probackup
      ansible.builtin.package:
        name:
          - pg-probackup-{{ pg_probackup_version }}
          - pg-probackup-{{ pg_probackup_version }}-dbg
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
  environment: "{{ proxy_env | default({}) }}"
  when:
    - installation_method == "repo"
    - ansible_os_family == "Debian"
    - pg_probackup_install_from_postgrespro_repo|bool
  tags: pg_probackup, pg_probackup_repo, pg_probackup_install

- block:  # RedHat family
    # RPM Centos Packages
    - name: Get pg_probackup-repo-centos.noarch.rpm
      ansible.builtin.get_url:
        url: "https://repo.postgrespro.ru/pg_probackup/keys/pg_probackup-repo-centos.noarch.rpm"
        dest: "/tmp/pg_probackup-repo.rpm"
        timeout: 30
        validate_certs: false
      when: ansible_distribution == 'CentOS'
    # RPM Oracle Linux Packages
    - name: Get pg_probackup-repo-oraclelinux.noarch.rpm
      ansible.builtin.get_url:
        url: "https://repo.postgrespro.ru/pg_probackup/keys/pg_probackup-repo-oraclelinux.noarch.rpm"
        dest: "/tmp/pg_probackup-repo.rpm"
        timeout: 30
        validate_certs: false
      when: ansible_distribution == 'OracleLinux'
    # RPM RHEL Packages
    - name: Get pg_probackup-repo-rhel.noarch.rpm
      ansible.builtin.get_url:
        url: "https://repo.postgrespro.ru/pg_probackup/keys/pg_probackup-repo-rhel.noarch.rpm"
        dest: "/tmp/pg_probackup-repo.rpm"
        timeout: 30
        validate_certs: false
      when:
        - ansible_distribution != 'CentOS'
        - ansible_distribution != 'OracleLinux'

    - name: Make sure pgdg repository is installed
      ansible.builtin.package:
        name: /tmp/pg_probackup-repo.rpm
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3

    - name: Clean dnf cache
      ansible.builtin.command: dnf clean all

    - name: Install pg_probackup
      ansible.builtin.package:
        name:
          - pg_probackup-{{ pg_probackup_version }}
          - pg_probackup-{{ pg_probackup_version }}-debuginfo
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
  environment: "{{ proxy_env | default({}) }}"
  when:
    - installation_method == "repo"
    - ansible_os_family == "RedHat"
    - pg_probackup_install_from_postgrespro_repo|bool
  tags: pg_probackup, pg_probackup_repo, pg_probackup_install

...
