---

- block:
    - name: Get system username
      become: false
      ansible.builtin.command: whoami
      register: system_user
      changed_when: false

    - name: "Add public keys to ~{{ system_user.stdout }}/.ssh/authorized_keys"
      ansible.posix.authorized_key:
        user: "{{ system_user.stdout }}"
        key: "{{ item }}"
        state: present
      loop: "{{ ssh_public_keys_list | map('replace', '\"', '') | map('replace', \"'\", \"\") | list }}"
      vars:
        ssh_public_keys_list: >-
          {{
            (ssh_public_keys
            | replace('\n', ',')
            | split(',')
            | map('trim')
            | list)
            if ssh_public_keys is string else ssh_public_keys
          }}
  when:
    - ssh_public_keys is defined
    - ssh_public_keys | length > 0
  tags: ssh_public_keys

...
