---

- name: Fetch files from the master
  run_once: true
  fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    flat: true
    validate_checksum: true
  loop: "{{ fetch_files_from_master }}"
  delegate_to: "{{ groups.master[0] }}"
  when:
    - fetch_files_from_master is defined
    - fetch_files_from_master | length > 0
  tags: fetch_files

- name: Copy files to all servers
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ copy_files_to_all_server }}"
  when:
    - copy_files_to_all_server is defined
    - copy_files_to_all_server | length > 0
  tags: copy_files

...
