---

# when postgresql NOT exists
- block:
    - name: PostgreSQL | check that data directory "{{ postgresql_data_dir }}" is not initialized
      stat:
        path: "{{ postgresql_data_dir }}/PG_VERSION"
      register: pgdata_initialized
      when: patroni_cluster_bootstrap_method == "initdb"

    - name: PostgreSQL | data directory check result
      fail:
        msg: "Whoops! data directory {{ postgresql_data_dir }} is already initialized"
      when:
        - pgdata_initialized.stat.exists is defined
        - pgdata_initialized.stat.exists
  when:
    - not postgresql_exists | bool
    - not (postgresql_cluster_maintenance|default(false)|bool) # exclude for config_pgcluster.yml

# when postgresql exists
- block:
    - name: PostgreSQL | check that data directory "{{ postgresql_data_dir }}" is initialized
      stat:
        path: "{{ postgresql_data_dir }}/PG_VERSION"
      register: pgdata_initialized

    - name: PostgreSQL | data directory check result
      fail:
        msg: "Whoops! data directory {{ postgresql_data_dir }} is not initialized"
      when:
        - pgdata_initialized.stat.exists is defined
        - not pgdata_initialized.stat.exists
  when:
    - postgresql_exists | bool
    - not (postgresql_cluster_maintenance|default(false)|bool) # exclude for config_pgcluster.yml
